SERVER_IP = '127.0.0.1'
SERVER_PORT = 8000
SERVER_PROTOCOL = 'http'
SERVER_URL = f'{SERVER_PROTOCOL}://{SERVER_IP}:{SERVER_PORT}'

REDIS_PORT = 8001
REDIS_IP = SERVER_IP

## Chat Service
SERVICE_CHAT_IP = SERVER_IP
SERVICE_CHAT_PORT = 8011
SERVICE_CHAT_REDIS_IP = SERVER_IP
SERVICE_CHAT_REDIS_PORT = 8012
SERVICE_CHAT_RMQ_IP = SERVER_IP
SERVICE_CHAT_RMQ_PORT = 5672

## Notification Service
SERVICE_NC_IP = SERVER_IP
SERVICE_NC_PORT = 8021
